### PR TITLE
blocking code in own thread

### PR DESCRIPTION
**Pull request by FedorSmirnov89**
changed the container manager so that it executes the blocking initImage and closeImage steps in an own thread (not managed by VertX).

### CODE REVIEW

**Comment by doetlingerlukas** [comment]
I refactored to code to use the async features of `docker-java`.
There is some weird bug in the image pulling process, where VertX claims that a promise has already been completed. Do you have any idea where this might be coming from?

**Comment by FedorSmirnov89** [comment]
Okay, 2 things: 

(a) the problem with completing the promise multiple times makes sense: The pull command produces multiple different async events signaling the different stages of pulling. I changed the method to only complete the promise if the pullEvent was successful and it seems to work fine.

(b) The waiting for the start of the containers does not work the way it is implemented with the WaitResponse, at least at my system. No wait events ever arrive, so that the enactment runs into a live lock here (in spite of the fact that the containers are up and running). In my push, I replaced the async waiting with actually setting a VertX timer. This would in principle work as a solution, but it would be great if you could look into the problem with the wait events.

**Comment by doetlingerlukas** [comment]
(a) seems to be resolved. Thanks for that!

(b) is now also resolved. I have implemented a custom function, which works well on my systems. The waiting for containers with the async callback seems to have some issue in `docker-java`. 

Please confirm if everything works for you.

**Review by doetlingerlukas — APPROVED** [review]

**Comment by doetlingerlukas** [comment]
https://github.com/docker-java/docker-java/issues/1831#issue-1155659697

**Comment by doetlingerlukas** [comment]
Turns out the error was on my side. `WaitContainerCmd` finishes if a containers stops.

**Comment by FedorSmirnov89** [comment]
Okay. Just tested it. Everything works perfectly on my system. Great 😄 , thank you 👍🏻 .

Will now merge this branch into master.

**Pull request merged**
